# Generated by Django 4.2.7 on 2023-11-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_drink_product_is_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoe_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
