# Generated by Django 4.2.7 on 2023-12-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_variant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
